import numpy as np
import pandas as pd

from b_eda import df

conditions = [
(df["product"] == "Abrahalls Lily The Pink"),
((df["product"] == "Cornish Orchards Dry Cider")),
((df["product"] == "Cornish Orchards Hedgerow Cider")),
((df["product"] == "Cotswold Cider Company Muscle Mary")),
((df["product"] == "Gwynt Y Ddraig Welsh Warrior")),
((df["product"] == "Harrys Dirty Harrys Raspberry And Blackcurrant Cider")),
((df["product"] == "Harrys Haymaker Dry Cider")),
((df["product"] == "Hawkes Dabinett")),
((df["product"] == "Hawkes Dead And Berried")),
((df["product"] == "Hawkes Doom and Bloom")),
((df["product"] == "Hawkes Pineapple Punch")),
((df["product"] == "Hawkes Urban Orchard")),
((df["product"] == "Hawkes Urban Orchard Mixed Berry")),
((df["product"] == "Healeys Cornish Rattler Original")),
((df["product"] == "Healeys Cornish Rattler Pineapple")),
((df["product"] == "Healeys Cornish Rattler Strawberry And Lime")),
((df["product"] == "Henry Westons Vintage")),
((df["product"] == "Hunts Hazy Dazy")),
((df["product"] == "Inchs")),
((df["product"] == "Kentish Pip Craftsman Cider")),
((df["product"] == "Kopparberg Mixed Fruits")),
((df["product"] == "Kopparberg Raspberry")),
((df["product"] == "Kopparberg Strawberry And Lime")),
((df["product"] == "Lilleys Apple and Blackberry")),
((df["product"] == "Lilleys Cherries And Berries")),
((df["product"] == "Lilleys Dark Sider")),
((df["product"] == "Lilleys Elderflower")),
((df["product"] == "Lilleys Lemon And Ginger")),
((df["product"] == "Lilleys Lemon and Lime")),
((df["product"] == "Lilleys Mango Cider (Cask)")),
((df["product"] == "Lilleys Merry Monkey Scrumpy")),
((df["product"] == "Lilleys Peach")),
((df["product"] == "Lilleys Pear And Raspberry (Cask)")),
((df["product"] == "Lilleys Pina Colada Cider")),
((df["product"] == "Lilleys Pineapple Cider")),
((df["product"] == "Lilleys Raspberry Mojito Cider")),
((df["product"] == "Lilleys Rhubarb")),
((df["product"] == "Lilleys Somerset Dry")),
((df["product"] == "Lilleys Somerset Medium Scrumpy")),
((df["product"] == "Lilleys Strawberry Cider")),
((df["product"] == "Lilleys Tropical Cider")),
((df["product"] == "Lilleys Welsh Warrior")),
((df["product"] == "Lilleys Wild Dog")),
((df["product"] == "Lilleys Woo Woo Cider")),
((df["product"] == "Magners Dark Fruit")),
((df["product"] == "Norcotts Rhubarb Cider")),
((df["product"] == "Old Mout Cider Berries & Cherries")),
((df["product"] == "Old Mout Cider Pineapple & Raspberry")),
((df["product"] == "Purbeck Dorset Blush")),
((df["product"] == "Rekorderlig Passion Fruit")),
((df["product"] == "Salcombe Rockfish Sea Cider")),
((df["product"] == "Sandford Orchard Berry Lane")),
((df["product"] == "Seacider Blood Orange")),
((df["product"] == "Sheppys Classic Draught Cider")),
((df["product"] == "Sheppys Farmhouse Cider Dry")),
((df["product"] == "Sheppys Original Cloudy Cider")),
((df["product"] == "Sheppys Raspberry Cider")),
((df["product"] == "Stowford Press Mixed Berries")),
((df["product"] == "Strongbow Rose")),
((df["product"] == "Sxollie Granny Smith Cider")),
((df["product"] == "Thatchers Blood Orange")),
((df["product"] == "Thatchers Cloudy Lemon")),
((df["product"] == "Thatchers Dark Berry")),
((df["product"] == "Thatchers Rose")),
((df["product"] == "Thatchers Stans Big Apple (Cask)")),
((df["product"] == "Thatchers Stans Trad")),
((df["product"] == "Thistly Cross Jaggy Thistle Medium Dry (Cask)")),
((df["product"] == "Thistly Cross Traditional Cider")),
((df["product"] == "Westons Caple Rd No 3")),
((df["product"] == "Westons Raspberry Roller")),
((df["product"] == "Westons Rosies Pig Rhubarb")),
((df["product"] == "Westons Rosies Pig Rusted Wheel")),
((df["product"] == "Westons Rosies Pig Strawberry and Elderflower"))
]
choices = [
"Fruit",
"Apple",
"Fruit",
"Fruit",
"Apple",
"Fruit",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Fruit",
"Apple",
"Fruit",
"Fruit",
"Apple",
"Apple",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Fruit",
"Fruit",
"Apple",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
"Apple",
"Apple",
"Apple",
"Apple",
"Fruit",
"Fruit",
"Fruit",
"Fruit",
]
for condition, choice in zip(conditions, choices):
    df.loc[condition, "cider_flavour"] = choice
print(df.head(10))

conditions = [
((df["product_class"] == "Premium Lager") * (df["product_segment"] == "Premium")),
#((df["product_class"] == "Premium Lager") * (df["cil_segment"] == "Premium")),
((df["product_segment"] == "Craft") * (df["product_class"] == "Premium Lager")),
((df["product_segment"] == "Classic") * (df["product_class"] == "Standard Lager")),
((df["product_segment"] == "Classic") * (df["product_class"] == "Premium Lager")),
((df["product_segment"] == "Mainstream") * (df["product_class"] == "Standard Lager")),
((df["product_segment"] == "Mainstream") * (df["product_class"] == "Premium Lager")),
((df["product_segment"] == "Craft") * (df["product_class"] == "Total Ale (Keg)")),
((df["product_segment"] == "Craft") * (df["product_class"] == "Total Ale (Cask)")),
((df["product_segment"] == "Classic") * (df["product_class"] == "Total Ale (Keg)")),
((df["product_segment"] == "Classic") * (df["product_class"] == "Total Ale (Cask)")),
(df["product_class"] == "Stout"),
((df["product_group"] == "Total Cider") * (df["cider_flavour"] == "Apple")),
((df["product_group"] == "Total Cider") * (df["cider_flavour"] == "Fruit"))

]

choices = [
"Premium Lager",
#"Premium Lager",
"Premium Lager",
"Classic Lager",
"Classic Lager",
"Mainstream Lager",
"Mainstream Lager",
"Craft Ale",
"Craft Ale",
"Classic Ale",
"Classic Ale",
"Stout",
"Apple Cider",
"Flavoured Cider"
]

df["custom_product_group"] = np.select(conditions, choices)

print(df.head(20))

df.loc[(df["brand"].isin(["Kopparberg"])) & (df["cider_flavour"] == "Fruit"), "product"] = "Kopparberg (all flavours)"
df.loc[(df["brand"].isin(["Old Mout Cider"])) & (df["cider_flavour"] == "Fruit"), "product"] = "Old Mout Cider (all flavours)"
df.loc[(df["brand"].isin(["Rekorderlig"])) & (df["cider_flavour"] == "Fruit"), "product"] = "Rekorderlig (all flavours)"
df.loc[(df["brand"].isin(["Bulmers"])) & (df["cider_flavour"] == "Fruit"), "product"] = "Bulmers (all flavours)"

print(df.head(20))